# fly.toml for DNSTT server
app = "dnstt-server-abdabdahfa"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 53
  protocol = "udp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    port = 8000

[env]
  DOMAIN = "dns.example.com"
